#!/usr/bin/env sh

set -e

set --

# TODO(feat): Parse blacklist from ~/.config/todogrep/todogreprc
_watchlist() {
  find "$WHERE" -type f -not -path '\./\.git/*' -exec grep -Iq . {} \; -printf "%P\0"
}

# TODO(feat): Beautify column output. Check out showtable.
_todogrep() {
  _watchlist |
    xargs -0 grep -on 'TODO([^)]*):.*' |
    sed 's/^\(.*\):\([0-9]\+\):TODO(\([^)]\+\)):\s*\(.*\)/\3‡\1‡\2‡\4‡/g' |
    sort |
    { printf '───\n‡Type‡File‡Line‡What\n───\n'; cat - ;} |
    column -t -s '‡'
}

[ -d "$1" ] && WHERE="$1" || WHERE='.'

case "$1" in
  -l|--watchlist)
    _watchlist | tr '\0' '\n'
    ;;
  *)
    _todogrep
    ;;
esac

# TODO(feat): cli arg for maxlen
# TODO(feat): README.md
